name: EVM compiler testing

on:
  pull_request:
    branches: [ evm-compiler ]

jobs:
  test:
    runs-on: [self-hosted, tests-runner]
    name: EVM compiler tests
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.22.x'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: gem install keccak256
      - name: Build
        run: bash llvm/projects/evm-tests/run_evm_tests.sh build
      - name: Run regression EVM tests
        run: bash llvm/projects/evm-tests/run_evm_tests.sh test
