name: EVM Backend Status CI

on:
  push:
    branches: [ 6-evm-cpp-frontend ]

jobs:
  build:

    runs-on: [self-hosted, tests-runner]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Set up cmake 3.16
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.16.x'
    - name: Install Geth
      run: |
        apt-get install software-properties-common
        add-apt-repository -y ppa:ethereum/ethereum
        apt-get update
        apt-get install ethereum
    - name: Run cmake
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD=EVM -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=EVM ../llvm
    - name: Build llc
      run: |
        cd ${{ github.workspace }}/build
        make -j4 llc
    - name: Run Integration tests
      run: |
        cd ${{ github.workspace }}/llvm/tools/evm-test
        python evm_test.py --llc-path ${{ github.workspace }}/build/bin/llc
